-- 1. Create the 'documents' bucket (Public)
insert into storage.buckets (id, name, public)
values ('documents', 'documents', true);

-- 2. Allow Public Access (View/Download)
create policy "Public Documents Access"
on storage.objects for select
in bucket 'documents'
using ( true );

-- 3. Allow Public Upload (Insert)
create policy "Public Documents Upload"
on storage.objects for insert
in bucket 'documents'
with check ( bucket_id = 'documents' );

-- 4. Allow Public Delete
create policy "Public Documents Delete"
on storage.objects for delete
in bucket 'documents'
using ( bucket_id = 'documents' );

-- 5. Create the 'documents' table
create table documents (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Enable RLS on table
alter table documents enable row level security;

-- 7. Table Policies (View/Insert/Delete)
create policy "Documents are viewable by everyone"
  on documents for select
  using ( true );

create policy "Anyone can upload documents"
  on documents for insert
  with check ( true );

create policy "Anyone can delete documents"
  on documents for delete
  using ( true );
