-- 1. Create the 'memories' bucket (Public)
insert into storage.buckets (id, name, public)
values ('memories', 'memories', true);

-- 2. Allow Public Access (View)
create policy "Public Access"
on storage.objects for select
in bucket 'memories'
using ( true );

-- 3. Allow Public Upload (Insert)
create policy "Public Upload"
on storage.objects for insert
in bucket 'memories'
with check ( bucket_id = 'memories' );

-- 4. Create the 'memories' table (if not exists)
create table memories (
  id bigint generated by default as identity primary key,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Enable RLS on table
alter table memories enable row level security;

-- 6. Table Policies
create policy "Public memories are viewable by everyone"
  on memories for select
  using ( true );

create policy "Anyone can upload memories"
  on memories for insert
  with check ( true );
